name: 'Test workflow'

on: workflow_dispatch

jobs:
  python-run:
    runs-on: ubuntu-latest
    steps:
      - name: "generate file"
        run: |
          echo "This is my text" > filename.txt
          pwd

  email:
    runs-on: ubuntu-latest
    needs: python-run
    steps:
      - name: 'Send Mail'
        uses: dawidd6/action-send-mail@v18
        with:
          server_address: smtp.gmail.com
          # connection_url: ${{ secrets.MAIL_CONNECTION }}
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions Test
          to: smartinez2@clevelandohio.gov,smurphy3@clevelandohio.gov
          from: LucasDePiglio@example.com
          body: file://filename.txt
