name: 'Test workflow'

on: workflow_dispatch

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: 'Send Mail'
        uses: dawidd6/action-send-mail@v18
        with:
          server_address: smtp.gmail.com
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions Test
          to: smartinez2@clevelandohio.gov,smurphy3@clevelandohio.gov
          from: LucasDePiglio@example.com
          body: I think we've got it
