name: 'Test workflow'

on: workflow_dispatch

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6
      - name: "Convert Notebook"
        run: |
          pip install jupyter
          pwd
          jupyter nbconvert --to-html x.ipynb
      - name: 'Send Mail'
        uses: dawidd6/action-send-mail@v18
        with:
          server_address: smtp.gmail.com
          # connection_url: ${{ secrets.MAIL_CONNECTION }}
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions Test
          to: smartinez2@clevelandohio.gov,smurphy3@clevelandohio.gov
          from: LucasDePiglio@example.com
          body: file://filename.txt
